services:
  portfolio:
    build: .
    environment:
      - NODE_ENV=production
      - PORT=80
    ports:
      - "80:80"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: always
    command: ["pm2-runtime", "start", "ecosystem.json"]
